version: "3.8"

services:
  app:
    container_name: app
    build: .
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations

    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    expose:
      - 5432
    env_file:
      - .env
